name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set the branch you want to trigger the workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Navigate to portfolio directory & install
        run: cd portfolio && npm install

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Export the project
        run: npm run export

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
